version: "3"
services:
  ecomposteira-notification:
    container_name: ecomposteira-notification
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - .:/app
      - /app/node_modules
